<a href="https://colab.research.google.com/github/Sanjan193/High-Entropy-Alloys-Comparative-Machine-Learning-for-Metal-State-Prediction/blob/main/Notebooks/Data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Imports**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from google.colab import files

In [ ]:
# checking the dataset
data = pd.read_csv("/content/1-s2.0-S2352340921006302-mmc1.csv",
                   encoding='latin1')

data.head(5).T

,0,1,2,3,4
Alloy ID,Alloy 0000,Alloy 0001,Alloy 0002,Alloy 0003,Alloy 0004
Alloy,Al0.5NbTaTiV,Al0.75MoNbTiV,Al0.25MoNbTiV,Al0.25NbTaTiV,Al0.2MoTaTiV
Al,0.111111,0.157895,0.058824,0.058824,0.047619
Co,0.0,0.0,0.0,0.0,0.0
Cr,0.0,0.0,0.0,0.0,0.0
Fe,0.0,0.0,0.0,0.0,0.0
Ni,0.0,0.0,0.0,0.0,0.0
Cu,0.0,0.0,0.0,0.0,0.0
Mn,0.0,0.0,0.0,0.0,0.0
Ti,0.222222,0.210526,0.235294,0.235294,0.238095
V,0.222222,0.210526,0.235294,0.235294,0.238095
Nb,0.222222,0.210526,0.235294,0.235294,0.0
Mo,0.0,0.210526,0.235294,0.0,0.238095
Zr,0.0,0.0,0.0,0.0,0.0
Hf,0.0,0.0,0.0,0.0,0.0
Ta,0.222222,0.0,0.0,0.235294,0.238095
W,0.0,0.0,0.0,0.0,0.0
C,0.0,0.0,0.0,0.0,0.0
Mg,0.0,0.0,0.0,0.0,0.0
Zn,0.0,0.0,0.0,0.0,0.0
Si,0.0,0.0,0.0,0.0,0.0
Re,0.0,0.0,0.0,0.0,0.0
N,0.0,0.0,0.0,0.0,0.0
Sc,0.0,0.0,0.0,0.0,0.0
Li,0.0,0.0,0.0,0.0,0.0
Sn,0.0,0.0,0.0,0.0,0.0
Be,0.0,0.0,0.0,0.0,0.0
Num_of_Elem,5.0,5.0,5.0,5.0,5.0
Density_calc,8.470882,6.606535,7.075664,8.805486,7.12885
dHmix,-8.395062,-9.351801,-4.041522,-4.816609,-3.356009
dSmix,13.145944,13.332806,12.70837,12.70837,12.569175
dGmix,575.784796,497.328753,546.1289,601.987509,551.958508
Tm,2215.832994,1915.290482,2098.157909,2312.760984,2119.418332
n.Para,3.897533,3.120047,7.456462,6.822791,8.960825
Atom.Size.Diff,3.737505,3.863332,4.003399,3.83244,4.017794
Elect.Diff,0.049616,0.232765,0.243217,0.050176,0.244333
VEC,4.555556,4.684211,4.882353,4.647059,4.904762
Sythesis_Route,AC,AC,AC,AC,AC
Hot-Cold_Working,NaN,NaN,NaN,NaN,NaN
Homogenization_Temp,NaN,NaN,NaN,NaN,NaN
Homogenization_Time,NaN,NaN,NaN,NaN,NaN
Annealing_Temp,NaN,NaN,NaN,NaN,NaN
Annealing_Time_(min),NaN,NaN,NaN,NaN,NaN
Quenching,NaN,NaN,NaN,NaN,NaN
HPR,NaN,NaN,NaN,NaN,NaN
Microstructure_,BCC,BCC,BCC,BCC,BCC
Multiphase,S,S,S,S,S
IM_Structure,NaN,NaN,NaN,NaN,NaN
Microstructure,BCC,BCC,BCC,BCC,BCC
Phases,BCC_SS,BCC_SS,BCC_SS,BCC_SS,BCC_SS
References,10.1016/j.proeng.2012.03.043,10.3390/e16020870,10.3390/e16020870,10.1016/j.proeng.2012.03.043,10.4028/www.scientific.net/MSF.898.638
Unnamed: 51,NaN,NaN,NaN,NaN,NaN
Unnamed: 52,NaN,NaN,NaN,NaN,NaN

In [ ]:
data['Phases'].unique()

array(['BCC_SS', 'Im', 'FCC_SS', 'FCC_PLUS_BCC', nan], dtype=object)

In [ ]:
k = data['Alloy '].unique()
len(k)
# data.columns

472

# **Dropping the unnecessary features**

In [ ]:
# dropping the text featres here to get the accurate numeric data rame
data.drop(columns=['Alloy ID','Quenching','HPR','Unnamed: 51','Annealing_Temp','Unnamed: 52','References','Hot-Cold_Working','IM_Structure','Alloy ','Microstructure_', 'Multiphase','Microstructure'],axis=1,inplace=True)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1361 entries, 0 to 1360
Data columns (total 40 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Al                    1360 non-null   float64
 1   Co                    1360 non-null   float64
 2   Cr                    1360 non-null   float64
 3   Fe                    1360 non-null   float64
 4   Ni                    1360 non-null   float64
 5   Cu                    1360 non-null   float64
 6   Mn                    1360 non-null   float64
 7   Ti                    1360 non-null   float64
 8   V                     1360 non-null   float64
 9   Nb                    1360 non-null   float64
 10  Mo                    1360 non-null   float64
 11  Zr                    1360 non-null   float64
 12  Hf                    1360 non-null   float64
 13  Ta                    1360 non-null   float64
 14  W                     1360 non-null   float64
 15  C                     1360 non-null   float64
 16  Mg                    1360 non-null   float64
 17  Zn                    1360 non-null   float64
 18  Si                    1360 non-null   float64
 19  Re                    1360 non-null   float64
 20  N                     1360 non-null   float64
 21  Sc                    1360 non-null   float64
 22  Li                    1360 non-null   float64
 23  Sn                    1360 non-null   float64
 24  Be                    1360 non-null   float64
 25  Num_of_Elem           1360 non-null   float64
 26  Density_calc          1355 non-null   float64
 27  dHmix                 1360 non-null   float64
 28  dSmix                 1360 non-null   float64
 29  dGmix                 1360 non-null   float64
 30  Tm                    1360 non-null   float64
 31  n.Para                1359 non-null   float64
 32  Atom.Size.Diff        1360 non-null   float64
 33  Elect.Diff            1360 non-null   float64
 34  VEC                   1360 non-null   float64
 35  Sythesis_Route        1360 non-null   object
 36  Homogenization_Temp   571 non-null    float64
 37  Homogenization_Time   561 non-null    float64
 38  Annealing_Time_(min)  594 non-null    float64
 39  Phases                1360 non-null   object
dtypes: float64(38), object(2)
memory usage: 425.4+ KB

To get the more refined data set I'm here dropping all the rows except the **"Annealing_Temp"** 603 values

"Sythesis_Route","Hot-Cold_Working","Annealing_Temp","Microstructure_","Multiphase","IM_Structure","Microstructure","Phases"

In [ ]:
# Final data set till here
df_final = data[data["Annealing_Time_(min)"].notnull()]

# **Fillling Null Values And Trnsforming The Text Data Into Embiddings**

In the data set 2 columns **'Homogenization_Temp', 'Homogenization_Time'** has only somme null value....

So I'm going to fill the 'Homogenization_Time' as the mode vale and the 'Homogenization_Temp' as the

In [ ]:
df_final['Homogenization_Temp'].fillna(df_final['Homogenization_Temp'].median(),inplace=True)
df_final['Homogenization_Time'].fillna(df_final['Homogenization_Time'].mode().iloc[0],inplace=True)

/tmp/ipykernel_6208/281746663.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['Homogenization_Temp'].fillna(df_final['Homogenization_Temp'].median(),inplace=True)
/tmp/ipykernel_6208/281746663.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Homogenization_Temp'].fillna(df_final['Homogenization_Temp'].median(),inplace=True)
/tmp/ipykernel_6208/281746663.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_final['Homogenization_Time'].fillna(df_final['Homogenization_Time'].mode().iloc[0],inplace=True)
/tmp/ipykernel_6208/281746663.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Homogenization_Time'].fillna(df_final['Homogenization_Time'].mode().iloc[0],inplace=True)

# **Encoding the text data into numbers**

In [ ]:
# for Sythesis Route
map1 = {
   'AC':1,
   'PM':2
}
# for phases
map2 = {
    'BCC_SS':1,
    'FCC_SS':2,
    'Im':3,
    'FCC_PLUS_BCC':4
}

df_final['Sythesis_Route'] = df_final['Sythesis_Route'].map(map1)
df_final['Phases'] = df_final['Phases'].map(map2)

/tmp/ipykernel_6208/783476561.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Sythesis_Route'] = df_final['Sythesis_Route'].map(map1)
/tmp/ipykernel_6208/783476561.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final['Phases'] = df_final['Phases'].map(map2)

In [ ]:
df_final.head(5).T

,5,6,7,16,17
Al,0.060000,0.060000,0.060000,0.200000,0.200000
Co,0.000000,0.000000,0.000000,0.000000,0.000000
Cr,0.000000,0.000000,0.000000,0.200000,0.200000
Fe,0.000000,0.000000,0.000000,0.000000,0.000000
Ni,0.000000,0.000000,0.000000,0.000000,0.000000
Cu,0.000000,0.000000,0.000000,0.000000,0.000000
Mn,0.000000,0.000000,0.000000,0.000000,0.000000
Ti,0.280000,0.280000,0.280000,0.200000,0.200000
V,0.040000,0.040000,0.040000,0.000000,0.000000
Nb,0.200000,0.200000,0.200000,0.200000,0.200000
Mo,0.000000,0.000000,0.000000,0.200000,0.200000
Zr,0.260000,0.260000,0.260000,0.000000,0.000000
Hf,0.000000,0.000000,0.000000,0.000000,0.000000
Ta,0.160000,0.160000,0.160000,0.000000,0.000000
W,0.000000,0.000000,0.000000,0.000000,0.000000
C,0.000000,0.000000,0.000000,0.000000,0.000000
Mg,0.000000,0.000000,0.000000,0.000000,0.000000
Zn,0.000000,0.000000,0.000000,0.000000,0.000000
Si,0.000000,0.000000,0.000000,0.000000,0.000000
Re,0.000000,0.000000,0.000000,0.000000,0.000000
N,0.000000,0.000000,0.000000,0.000000,0.000000
Sc,0.000000,0.000000,0.000000,0.000000,0.000000
Li,0.000000,0.000000,0.000000,0.000000,0.000000
Sn,0.000000,0.000000,0.000000,0.000000,0.000000
Be,0.000000,0.000000,0.000000,0.000000,0.000000
Num_of_Elem,6.000000,6.000000,6.000000,5.000000,5.000000
Density_calc,7.710000,7.710000,7.710000,6.570000,6.570000
dHmix,-4.860000,-4.860000,-4.860000,-13.600000,-13.600000
dSmix,13.460000,13.460000,13.460000,13.380000,13.380000
dGmix,601.216955,601.216955,601.216955,555.596566,555.596566
Tm,2316.490000,2316.490000,2316.490000,2140.090000,2140.090000
n.Para,6.410000,6.410000,6.410000,2.110000,2.110000
Atom.Size.Diff,4.500000,4.500000,4.500000,4.870000,4.870000
Elect.Diff,0.110000,0.110000,0.110000,0.230000,0.230000
VEC,4.340000,4.340000,4.340000,4.800000,4.800000
Sythesis_Route,1.000000,1.000000,1.000000,1.000000,1.000000
Homogenization_Temp,1400.000000,1400.000000,1400.000000,1200.000000,1200.000000
Homogenization_Time,120.000000,120.000000,120.000000,120.000000,120.000000
Annealing_Time_(min),1440.000000,1440.000000,1440.000000,1200.000000,1200.000000
Phases,1.000000,1.000000,1.000000,2.000000,2.000000

# **Downloading the cleaned csv data**

In [ ]:
df_final.to_csv('cleaned_dataframe.csv', index=False)

# 2. Download the CSV file directly to your local computer
files.download('cleaned_dataframe.csv')